

paths:
  local_path: /tmp/app
  predict_model_path: ../models-release/master-ckpt-frozen/
  superresolve_model_path: /app/supres-40k-swir/
  output_dir : /tmp/app
  bucket_name : bucketsvmk
  blob_path : cameroon

flags:
  ul_flag: false
  no_cleanup: false
  reprocess: false
  redownload: false
  redownload_s1: false
  gen_feats: false
  gen_composite: false
  process: true
  snow: false
  make_training_data: false

tile_processing:
  year: 2024
  length: 4
  n_tiles: null
  x: 3451
  y: 1924
  start: 0
  end: 100000
  n_rows: 8
  lon: 11.9034 
  lat: 6.225
  country: cameroon
