

paths:
  local_path: tmp/app/
  superresolve_model_path: /app/supres-40k-swir/


flags:
  ul_flag: false
  no_cleanup: false
  reprocess: false
  redownload: false
  redownload_s1: false
  gen_feats: false
  gen_composite: false
  process: true
  snow: false
  make_training_data: false

tile_processing:
  length: 4
  n_tiles: null
  x: null
  y: null
  start: 0
  end: 100000
  n_rows: 8
